
export const DOMAIN = "http://localhost:3001/student";
export const LIMIT = 5;
// HTTP method 
export const HTTP_READ = "GET"
export const HTTP_CREATE = "POST"
export const HTTP_UPDATE = "PUT"
export const HTTP_DELETE = "DELETE"

// HTTP headers
export const HTTP_HEADER_JSON = {"Content-Type": "Application/json"}
export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST'
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS'
export const GET_STUDENT_FAILURE = 'GET_STUDENT_FAILURE'

export const ADD_STUDENT_REQUEST = 'ADD_STUDENT_REQUEST'
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE'

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST'
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE'

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST'
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE'

export const SEARCH_STUDENT_REQUEST = 'SEARCH_STUDENT_REQUEST'
export const SEARCH_STUDENT_SUCCESS = 'SEARCH_STUDENT_SUCCESS'
export const SEARCH_STUDENT_FAILURE = 'SEARCH_STUDENT_FAILURE'

export const PAGINATION_STUDENT_REQUEST = 'PAGINATION_STUDENT_REQUEST'
export const PAGINATION_STUDENT_SUCCESS = 'PAGINATION_STUDENT_SUCCESS'
export const PAGINATION_STUDENT_FAILURE = 'PAGINATION_STUDENT_FAILURE'
